spring:
  application.name: gate-keeper
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8081
          predicates:
            - Path=/service1/**
          filters:
            - RewritePath=/service1(?<remaining>/?.*), $\{remaining}
        - id: service2
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@IPAddressKeyResolver}"
            - RewritePath=/service2(?<remaining>/?.*), $\{remaining}
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.data.redis: DEBUG